// Shared UI class names. Keeping these in one place is what makes the interface
// feel like one system instead of a collection of ad-hoc buttons and cards.
export const iconButton = 'icon-button'
export const primaryButton = 'primary-button'
export const secondaryButton = 'secondary-button'
export const ghostButton = 'ghost-button'
export const textButton = 'text-button'
export const linkButton = 'link-button'
export const field = 'field'
export const sidebarRow = 'sidebar-row'
export const pickerRow = 'picker-row'
export const modalBackdrop = 'modal-backdrop'
export const modalCard = 'modal-card'
export const modalHeader = 'modal-header'
export const modalTitle = 'modal-title'
export const modalBody = 'modal-body'
export const modalFooter = 'modal-footer'
export const menu = 'menu'
export const menuItem = 'menu-item'
export const composerCard = 'composer-card'
export const submitButton = 'submit-button'
export const chip = 'chip'
export const chipRemove = 'chip-remove'
export const transcriptUser = 'transcript-user'
export const toolCard = 'tool-card'
export const emptyState = 'empty-state'
export const disclosureButton = 'disclosure-button'

export const statusDot = state => `status-dot status-dot--${state || 'idle'}`
